# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stack_obs <- function(nn, p, r = 0L) {
    .Call('_seasonality_stack_obs', PACKAGE = 'seasonality', nn, p, r)
}

last_year_holiday <- function(today, this_holiday, last_holiday) {
    .Call('_seasonality_last_year_holiday', PACKAGE = 'seasonality', today, this_holiday, last_holiday)
}

last_year <- function(today) {
    .Call('_seasonality_last_year', PACKAGE = 'seasonality', today)
}

years_ago <- function(today, shift) {
    .Call('_seasonality_years_ago', PACKAGE = 'seasonality', today, shift)
}

next_year_holiday <- function(today, this_holiday, next_holiday) {
    .Call('_seasonality_next_year_holiday', PACKAGE = 'seasonality', today, this_holiday, next_holiday)
}

next_year <- function(today) {
    .Call('_seasonality_next_year', PACKAGE = 'seasonality', today)
}

which_date_leq <- function(date, Dvec) {
    .Call('_seasonality_which_date_leq', PACKAGE = 'seasonality', date, Dvec)
}

which_date_geq <- function(date, Dvec) {
    .Call('_seasonality_which_date_geq', PACKAGE = 'seasonality', date, Dvec)
}

which_date_closest <- function(date, Dvec) {
    .Call('_seasonality_which_date_closest', PACKAGE = 'seasonality', date, Dvec)
}

which_date_closest_ordered <- function(FromVec, IndVec) {
    .Call('_seasonality_which_date_closest_ordered', PACKAGE = 'seasonality', FromVec, IndVec)
}

day <- function(date) {
    .Call('_seasonality_day', PACKAGE = 'seasonality', date)
}

replace_day <- function(date, new_day) {
    .Call('_seasonality_replace_day', PACKAGE = 'seasonality', date, new_day)
}

MonthDays <- function(year, month) {
    .Call('_seasonality_MonthDays', PACKAGE = 'seasonality', year, month)
}

end_of_month <- function(date) {
    .Call('_seasonality_end_of_month', PACKAGE = 'seasonality', date)
}

end_next_month <- function(date) {
    .Call('_seasonality_end_next_month', PACKAGE = 'seasonality', date)
}

end_previous_month <- function(date) {
    .Call('_seasonality_end_previous_month', PACKAGE = 'seasonality', date)
}

end_of_month_date <- function(date) {
    .Call('_seasonality_end_of_month_date', PACKAGE = 'seasonality', date)
}

first_of_month <- function(date) {
    .Call('_seasonality_first_of_month', PACKAGE = 'seasonality', date)
}

end_of_quarter <- function(date) {
    .Call('_seasonality_end_of_quarter', PACKAGE = 'seasonality', date)
}

first_previous_quarter <- function(date) {
    .Call('_seasonality_first_previous_quarter', PACKAGE = 'seasonality', date)
}

month_diff <- function(first_date, second_date) {
    .Call('_seasonality_month_diff', PACKAGE = 'seasonality', first_date, second_date)
}

ps_week <- function(day) {
    .Call('_seasonality_ps_week', PACKAGE = 'seasonality', day)
}

pseudo_weekly_sequence <- function(start, length = 0L, end = 0L) {
    .Call('_seasonality_pseudo_weekly_sequence', PACKAGE = 'seasonality', start, length, end)
}

pseudo_weekly_date <- function(date) {
    .Call('_seasonality_pseudo_weekly_date', PACKAGE = 'seasonality', date)
}

numeric_to_date <- function(year, month, day) {
    .Call('_seasonality_numeric_to_date', PACKAGE = 'seasonality', year, month, day)
}

SARMA <- function(Y, p, q, P, Q, P_lag, Q_lag) {
    .Call('_seasonality_SARMA', PACKAGE = 'seasonality', Y, p, q, P, Q, P_lag, Q_lag)
}

